/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author 23.01425-3
 */
public class TelaJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sairButton = new javax.swing.JButton();
        nomeUsuarioLabel = new javax.swing.JLabel();
        aparecidoIconLabel = new javax.swing.JLabel();
        dadoButton = new javax.swing.JButton();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sairButton.setBackground(new java.awt.Color(16, 31, 53));
        sairButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sairButton.setForeground(new java.awt.Color(255, 255, 255));
        sairButton.setText("sair");
        sairButton.setBorderPainted(false);
        sairButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sairButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1162, 60, 70, 20));

        nomeUsuarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeUsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nomeUsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 20, 80, 30));

        aparecidoIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pixil-frame-0__1__Easy-Resize.com-removebg-preview.png"))); // NOI18N
        getContentPane().add(aparecidoIconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, -1, -1));

        dadoButton.setText("dado");
        dadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dadoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, -1, -1));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doska appeared.png"))); // NOI18N
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairButtonActionPerformed
        var telaGameOver = new TelaGameOver();
        telaGameOver.setVisible(true);
        dispose();
    }//GEN-LAST:event_sairButtonActionPerformed

    private void dadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoButtonActionPerformed
        // quando o dado for ativado, vai gerar um número de um a seis (depois vemos como fazer isso)
        
    }//GEN-LAST:event_dadoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aparecidoIconLabel;
    private javax.swing.JButton dadoButton;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JButton sairButton;
    private javax.swing.JLabel telaLabel;
    // End of variables declaration//GEN-END:variables
}
