/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

/**
 *
 * @author 23.01425-3
 */
public class TelaQuestao extends javax.swing.JFrame {

    /**
     * Creates new form telaQuestao
     */
    public TelaQuestao() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        responderButton = new javax.swing.JButton();
        AlternativaA = new javax.swing.JRadioButton();
        AlternativaB = new javax.swing.JRadioButton();
        AlternativaC = new javax.swing.JRadioButton();
        AlternativaD = new javax.swing.JRadioButton();
        responderButtonLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        telaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        responderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/responderButtonImage.png"))); // NOI18N
        responderButton.setBorderPainted(false);
        responderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        responderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responderButtonActionPerformed(evt);
            }
        });
        getContentPane().add(responderButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 490, 190, 60));

        buttonGroup1.add(AlternativaA);
        AlternativaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlternativaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaAActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        buttonGroup1.add(AlternativaB);
        AlternativaB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AlternativaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlternativaBActionPerformed(evt);
            }
        });
        getContentPane().add(AlternativaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 98, -1));

        buttonGroup1.add(AlternativaC);
        AlternativaC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(AlternativaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        buttonGroup1.add(AlternativaD);
        AlternativaD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(AlternativaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, -1, -1));

        responderButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/responderButtonImage.png"))); // NOI18N
        getContentPane().add(responderButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("shishdihdhdhde\n]joej\n\n\ndjididjicdjcididcjididjcid\nddmjidjdddicjc\njdicidc");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 570, -1));

        telaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/telaPerguntaImage.png"))); // NOI18N
        getContentPane().add(telaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void responderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responderButtonActionPerformed

    private void AlternativaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlternativaAActionPerformed

    private void AlternativaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlternativaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlternativaBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuestao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuestao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AlternativaA;
    private javax.swing.JRadioButton AlternativaB;
    private javax.swing.JRadioButton AlternativaC;
    private javax.swing.JRadioButton AlternativaD;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton responderButton;
    private javax.swing.JLabel responderButtonLabel;
    private javax.swing.JLabel telaLabel;
    // End of variables declaration//GEN-END:variables
}
